apiVersion: v1
kind: Service
metadata:
  labels:
    app: udafrontend
  name: udafrontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udafrontend-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: udafrontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
