apiVersion: v1
kind: Service
metadata:
  labels:
    app: userapp
  name: userapp-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/userapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: userapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
